//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ez.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EzLanguage {
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Back {
            get {
                return ResourceManager.GetString("COM_Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Broswer {
            get {
                return ResourceManager.GetString("COM_Btn_Broswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Close {
            get {
                return ResourceManager.GetString("COM_Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Comfirm {
            get {
                return ResourceManager.GetString("COM_Btn_Comfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Delete {
            get {
                return ResourceManager.GetString("COM_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        public static string COM_Btn_EndPage {
            get {
                return ResourceManager.GetString("COM_Btn_EndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string COM_Btn_FistPage {
            get {
                return ResourceManager.GetString("COM_Btn_FistPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进 的本地化字符串。
        /// </summary>
        public static string COM_Btn_GoAhead {
            get {
                return ResourceManager.GetString("COM_Btn_GoAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        public static string COM_Btn_GoBack {
            get {
                return ResourceManager.GetString("COM_Btn_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string COM_Btn_NextPage {
            get {
                return ResourceManager.GetString("COM_Btn_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string COM_Btn_PrePage {
            get {
                return ResourceManager.GetString("COM_Btn_PrePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Reset {
            get {
                return ResourceManager.GetString("COM_Btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Save {
            get {
                return ResourceManager.GetString("COM_Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Submit {
            get {
                return ResourceManager.GetString("COM_Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public static string COM_Btn_UnDo {
            get {
                return ResourceManager.GetString("COM_Btn_UnDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string COM_Btn_Update {
            get {
                return ResourceManager.GetString("COM_Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期日,星期一,星期二,星期三,星期四,星期五,星期六 的本地化字符串。
        /// </summary>
        public static string COM_JS_Week {
            get {
                return ResourceManager.GetString("COM_JS_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户或密码错误！ 的本地化字符串。
        /// </summary>
        public static string COM_Msg_AccountError {
            get {
                return ResourceManager.GetString("COM_Msg_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败！ 的本地化字符串。
        /// </summary>
        public static string COM_Msg_AddFail {
            get {
                return ResourceManager.GetString("COM_Msg_AddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        public static string COM_Msg_AddSuccess {
            get {
                return ResourceManager.GetString("COM_Msg_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败！ 的本地化字符串。
        /// </summary>
        public static string COM_Msg_EditFail {
            get {
                return ResourceManager.GetString("COM_Msg_EditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        public static string COM_Msg_EditSuccess {
            get {
                return ResourceManager.GetString("COM_Msg_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败！ 的本地化字符串。
        /// </summary>
        public static string COM_Msg_SaveFail {
            get {
                return ResourceManager.GetString("COM_Msg_SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        public static string COM_Msg_SaveSuccess {
            get {
                return ResourceManager.GetString("COM_Msg_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户信息 的本地化字符串。
        /// </summary>
        public static string COM_N_AccountInfo {
            get {
                return ResourceManager.GetString("COM_N_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户管理 的本地化字符串。
        /// </summary>
        public static string COM_N_AccountManage {
            get {
                return ResourceManager.GetString("COM_N_AccountManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string COM_N_Address {
            get {
                return ResourceManager.GetString("COM_N_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string COM_N_Age {
            get {
                return ResourceManager.GetString("COM_N_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        public static string COM_N_BackSize {
            get {
                return ResourceManager.GetString("COM_N_BackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换语言 的本地化字符串。
        /// </summary>
        public static string COM_N_ChangeLang {
            get {
                return ResourceManager.GetString("COM_N_ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string COM_N_ChangePwd {
            get {
                return ResourceManager.GetString("COM_N_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string COM_N_Close {
            get {
                return ResourceManager.GetString("COM_N_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string COM_N_Company {
            get {
                return ResourceManager.GetString("COM_N_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面背景 的本地化字符串。
        /// </summary>
        public static string COM_N_DeskBg {
            get {
                return ResourceManager.GetString("COM_N_DeskBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱地址 的本地化字符串。
        /// </summary>
        public static string COM_N_Email {
            get {
                return ResourceManager.GetString("COM_N_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string COM_N_Gender {
            get {
                return ResourceManager.GetString("COM_N_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好 的本地化字符串。
        /// </summary>
        public static string COM_N_Hello {
            get {
                return ResourceManager.GetString("COM_N_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证 的本地化字符串。
        /// </summary>
        public static string COM_N_IdCard {
            get {
                return ResourceManager.GetString("COM_N_IdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登录IP 的本地化字符串。
        /// </summary>
        public static string COM_N_LastLoginIP {
            get {
                return ResourceManager.GetString("COM_N_LastLoginIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登陆时间 的本地化字符串。
        /// </summary>
        public static string COM_N_LastLoginTime {
            get {
                return ResourceManager.GetString("COM_N_LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string COM_N_Login {
            get {
                return ResourceManager.GetString("COM_N_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public static string COM_N_LoginName {
            get {
                return ResourceManager.GetString("COM_N_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录次数 的本地化字符串。
        /// </summary>
        public static string COM_N_LoginNum {
            get {
                return ResourceManager.GetString("COM_N_LoginNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string COM_N_Menu {
            get {
                return ResourceManager.GetString("COM_N_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        public static string COM_N_Mobile {
            get {
                return ResourceManager.GetString("COM_N_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多角色用户 的本地化字符串。
        /// </summary>
        public static string COM_N_MutilRole {
            get {
                return ResourceManager.GetString("COM_N_MutilRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}页 的本地化字符串。
        /// </summary>
        public static string COM_N_OnNPage {
            get {
                return ResourceManager.GetString("COM_N_OnNPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前页 的本地化字符串。
        /// </summary>
        public static string COM_N_PageState {
            get {
                return ResourceManager.GetString("COM_N_PageState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string COM_N_Password {
            get {
                return ResourceManager.GetString("COM_N_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 =请选择= 的本地化字符串。
        /// </summary>
        public static string COM_N_PleaseSelect {
            get {
                return ResourceManager.GetString("COM_N_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        public static string COM_N_QQ {
            get {
                return ResourceManager.GetString("COM_N_QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册IP 的本地化字符串。
        /// </summary>
        public static string COM_N_RegIP {
            get {
                return ResourceManager.GetString("COM_N_RegIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string COM_N_Regist {
            get {
                return ResourceManager.GetString("COM_N_Regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册时间 的本地化字符串。
        /// </summary>
        public static string COM_N_RegTime {
            get {
                return ResourceManager.GetString("COM_N_RegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷 的本地化字符串。
        /// </summary>
        public static string COM_N_Shortcut {
            get {
                return ResourceManager.GetString("COM_N_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统基本信息 的本地化字符串。
        /// </summary>
        public static string COM_N_SystemBaseInfo {
            get {
                return ResourceManager.GetString("COM_N_SystemBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        public static string COM_N_SystemSet {
            get {
                return ResourceManager.GetString("COM_N_SystemSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 座机 的本地化字符串。
        /// </summary>
        public static string COM_N_Tel {
            get {
                return ResourceManager.GetString("COM_N_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public static string COM_N_ToMax {
            get {
                return ResourceManager.GetString("COM_N_ToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public static string COM_N_ToMin {
            get {
                return ResourceManager.GetString("COM_N_ToMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共{0}条数据 的本地化字符串。
        /// </summary>
        public static string COM_N_TotalData {
            get {
                return ResourceManager.GetString("COM_N_TotalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总页数 的本地化字符串。
        /// </summary>
        public static string COM_N_TotalPage {
            get {
                return ResourceManager.GetString("COM_N_TotalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string COM_N_UserName {
            get {
                return ResourceManager.GetString("COM_N_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        public static string COM_N_Window {
            get {
                return ResourceManager.GetString("COM_N_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完善资料 的本地化字符串。
        /// </summary>
        public static string COM_V_PerfectInfo {
            get {
                return ResourceManager.GetString("COM_V_PerfectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能 的本地化字符串。
        /// </summary>
        public static string COM_Var_Cant {
            get {
                return ResourceManager.GetString("COM_Var_Cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否 的本地化字符串。
        /// </summary>
        public static string COM_Var_IsOrNot {
            get {
                return ResourceManager.GetString("COM_Var_IsOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许 的本地化字符串。
        /// </summary>
        public static string COM_Var_NotAllowed {
            get {
                return ResourceManager.GetString("COM_Var_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法 的本地化字符串。
        /// </summary>
        public static string COM_Var_NoWay {
            get {
                return ResourceManager.GetString("COM_Var_NoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据已存在不允许进行相关操作! 的本地化字符串。
        /// </summary>
        public static string SYS_Exp_DataExits {
            get {
                return ResourceManager.GetString("SYS_Exp_DataExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词条数据被使用不能执行{0}操作! 的本地化字符串。
        /// </summary>
        public static string SYS_Exp_DataHadRef {
            get {
                return ResourceManager.GetString("SYS_Exp_DataHadRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据存在引用 的本地化字符串。
        /// </summary>
        public static string SYS_Exp_DataHasRef {
            get {
                return ResourceManager.GetString("SYS_Exp_DataHasRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门信息不存在 的本地化字符串。
        /// </summary>
        public static string SYS_Exp_DepInfoNotExits {
            get {
                return ResourceManager.GetString("SYS_Exp_DepInfoNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此类实例中未找到调用的属性{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Exp_NoProperty {
            get {
                return ResourceManager.GetString("SYS_Exp_NoProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用了不被支持的类型！ 的本地化字符串。
        /// </summary>
        public static string SYS_Exp_UnSupportType {
            get {
                return ResourceManager.GetString("SYS_Exp_UnSupportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户信息 的本地化字符串。
        /// </summary>
        public static string SYS_M_AccountInfo {
            get {
                return ResourceManager.GetString("SYS_M_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户管理 的本地化字符串。
        /// </summary>
        public static string SYS_M_AccountManager {
            get {
                return ResourceManager.GetString("SYS_M_AccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户 的本地化字符串。
        /// </summary>
        public static string SYS_M_AddUser {
            get {
                return ResourceManager.GetString("SYS_M_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换语言 的本地化字符串。
        /// </summary>
        public static string SYS_M_ChangeLang {
            get {
                return ResourceManager.GetString("SYS_M_ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string SYS_M_ChangePwd {
            get {
                return ResourceManager.GetString("SYS_M_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面背景 的本地化字符串。
        /// </summary>
        public static string SYS_M_DeskBg {
            get {
                return ResourceManager.GetString("SYS_M_DeskBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string SYS_M_Menu {
            get {
                return ResourceManager.GetString("SYS_M_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化 的本地化字符串。
        /// </summary>
        public static string SYS_M_Personalize {
            get {
                return ResourceManager.GetString("SYS_M_Personalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统信息 的本地化字符串。
        /// </summary>
        public static string SYS_M_SysInfo {
            get {
                return ResourceManager.GetString("SYS_M_SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        public static string SYS_M_SysSet {
            get {
                return ResourceManager.GetString("SYS_M_SysSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优碧特软件（西安）软件有限公司 的本地化字符串。
        /// </summary>
        public static string SYS_N_CompanyName {
            get {
                return ResourceManager.GetString("SYS_N_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优碧特软件（西安）软件有限公司 的本地化字符串。
        /// </summary>
        public static string SYS_N_Copyright {
            get {
                return ResourceManager.GetString("SYS_N_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础框架，公司产品底层框架 的本地化字符串。
        /// </summary>
        public static string SYS_N_Description {
            get {
                return ResourceManager.GetString("SYS_N_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ez 的本地化字符串。
        /// </summary>
        public static string SYS_N_SystemName {
            get {
                return ResourceManager.GetString("SYS_N_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v1.0.0.0 的本地化字符串。
        /// </summary>
        public static string SYS_N_Version {
            get {
                return ResourceManager.GetString("SYS_N_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级管理员 的本地化字符串。
        /// </summary>
        public static string Sys_R_SAdmin {
            get {
                return ResourceManager.GetString("Sys_R_SAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string SYS_V_LoginOut {
            get {
                return ResourceManager.GetString("SYS_V_LoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的内容不合法请检查！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_ComMsg {
            get {
                return ResourceManager.GetString("SYS_Val_ComMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请正确输入日期！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_Date {
            get {
                return ResourceManager.GetString("SYS_Val_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}应为邮件格式！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_Email {
            get {
                return ResourceManager.GetString("SYS_Val_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的值必须大于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_GreaterThan {
            get {
                return ResourceManager.GetString("SYS_Val_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应大于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_GreaterThanLen {
            get {
                return ResourceManager.GetString("SYS_Val_GreaterThanLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应大于或等于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_GreaterThanLenOrEqual {
            get {
                return ResourceManager.GetString("SYS_Val_GreaterThanLenOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的值必须大于或等于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("SYS_Val_GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的身份证号码！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_IdCard {
            get {
                return ResourceManager.GetString("SYS_Val_IdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入整数！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_Int {
            get {
                return ResourceManager.GetString("SYS_Val_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的值必须小于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_LessThan {
            get {
                return ResourceManager.GetString("SYS_Val_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应小于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_LessThanLen {
            get {
                return ResourceManager.GetString("SYS_Val_LessThanLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应小于或等于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_LessThanLenOrEqual {
            get {
                return ResourceManager.GetString("SYS_Val_LessThanLenOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的值必须小于或等于{0}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_LessThanOrEqual {
            get {
                return ResourceManager.GetString("SYS_Val_LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请正确输入手机号码! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_MobileNumber {
            get {
                return ResourceManager.GetString("SYS_Val_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入的{0}不一致！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_NotEqal {
            get {
                return ResourceManager.GetString("SYS_Val_NotEqal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址格式不正确！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_NotIP {
            get {
                return ResourceManager.GetString("SYS_Val_NotIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url格式不正确！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_NotUrl {
            get {
                return ResourceManager.GetString("SYS_Val_NotUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是数字！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_Number {
            get {
                return ResourceManager.GetString("SYS_Val_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请正确输入座机号码:格式可以是xxx-xxxxxxxx 的本地化字符串。
        /// </summary>
        public static string SYS_Val_PhoneNumber {
            get {
                return ResourceManager.GetString("SYS_Val_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请正确输入邮编！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_PostCode {
            get {
                return ResourceManager.GetString("SYS_Val_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的数字应大于{0}小于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_Range {
            get {
                return ResourceManager.GetString("SYS_Val_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应大于{0}小于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_RangeLen {
            get {
                return ResourceManager.GetString("SYS_Val_RangeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应大于{0}小于或等于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_RangeLenOrEqMax {
            get {
                return ResourceManager.GetString("SYS_Val_RangeLenOrEqMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应大于或等于{0}小于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_RangeLenOrEqMin {
            get {
                return ResourceManager.GetString("SYS_Val_RangeLenOrEqMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符长度应大于等于{0}或小于等于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_RangeLenOrEqual {
            get {
                return ResourceManager.GetString("SYS_Val_RangeLenOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的数字应大于{0}小于或等于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_RangeOrEqMax {
            get {
                return ResourceManager.GetString("SYS_Val_RangeOrEqMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的数字应大于或等于{0}小于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_RangeOrEqMin {
            get {
                return ResourceManager.GetString("SYS_Val_RangeOrEqMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的数字应大于等于{0}或小于等于{1}! 的本地化字符串。
        /// </summary>
        public static string SYS_Val_RangeOrEqual {
            get {
                return ResourceManager.GetString("SYS_Val_RangeOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}为必填项！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_Required {
            get {
                return ResourceManager.GetString("SYS_Val_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须以&quot;{1}&quot;开头！ 的本地化字符串。
        /// </summary>
        public static string SYS_Val_StartWith {
            get {
                return ResourceManager.GetString("SYS_Val_StartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string SYS_Val_StartWithComfirm {
            get {
                return ResourceManager.GetString("SYS_Val_StartWithComfirm", resourceCulture);
            }
        }
    }
}
